/* OldGameVM modification notice
 * This file was changed for OldGameVM in July 2026.
 * It is not the original file. See NOTICE.md.
 */
// generated by Fast Light User Interface Designer (fluid) version 1.0309
// OGVM-LAYOUTB: hand-edited (no fluid on build machine)

#ifndef StracciatellaLauncher_h
#define StracciatellaLauncher_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Round_Button.H>   /* OGVM-RADIO */
#include <FL/Fl_Progress.H>   /* OGVM-PROGRESS */
#include "ControllerView.h"
class StracciatellaLauncher {
public:
  StracciatellaLauncher();
  Fl_Double_Window *stracciatellaLauncher;
  Fl_Tabs *tabs;
  Fl_Button *editorButton;
  Fl_Button *playButton;
  Fl_Input *gameDirectoryInput;
  Fl_Button *browseJa2DirectoryButton;
  Fl_Choice *gameVersionInput;
  Fl_Button *guessVersionButton;
  Fl_Button *detectEditionButton;
  Fl_Button *importGameDataButton;
  Fl_Round_Button *sourceInstallerRadio;   /* OGVM-RADIO */
  Fl_Round_Button *sourceFolderRadio;
  Fl_Box *sourceStatusLabel;
  Fl_Progress *importProgress;   /* OGVM-PROGRESS */
  Fl_Group *ogvmInstallerPanel;   /* OGVM-LAYOUTB */
  Fl_Group *ogvmFolderPanel;      /* OGVM-LAYOUTB */
  Fl_Input *saveGameDirectoryInput;
  Fl_Button *browseSaveGameDirectoryButton;
  Fl_Browser *enabledModsBrowser;
  Fl_Button *enableModsButton;
  Fl_Button *disableModsButton;
  Fl_Button *moveUpModsButton;
  Fl_Button *moveDownModsButton;
  Fl_Browser *availableModsBrowser;
  Fl_Text_Display *modDetails;
  Fl_Output *gameSettingsOutput;
  Fl_Value_Input *resolutionXInput;
  Fl_Value_Input *resolutionYInput;
  Fl_Menu_Button *predefinedResolutionMenuButton;
  Fl_Box *invalidResolutionLabel;
  Fl_Choice *scalingModeChoice;
  Fl_Check_Button *fullscreenCheckbox;
  Fl_Check_Button *playSoundsCheckbox;
  /* OGVM-CONTROLLER: pad center, kind/value around (x360ce-ish). */
  static const int kPadBindCount = 14;
  Fl_Check_Button *controllerEnableToggle;
  Fl_Choice *controllerLayoutChoice;
  Fl_Choice *leftStickModeChoice;
  Fl_Choice *rightStickModeChoice;
  ControllerView *controllerView;
  Fl_Box *controllerStatusLabel;
  Fl_Text_Display *controllerHelp;
  Fl_Scroll *controllerBindScroll; /* unused (null); kept for ABI of generated layout */
  Fl_Choice *padKindChoice[14];  /* empty / Keyboard / Mouse Button / Wheel / Motion */
  Fl_Choice *padValueChoice[14]; /* specific key or button */
  Fl_Box *padLabel[14];
  Fl_Box *leftStickLabel;
  Fl_Box *rightStickLabel;
  Fl_Box *touchpadSensLabel; /* PS5 only */
  Fl_Choice *touchpadModeChoice; /* Cursor | Button */
  Fl_Value_Slider *touchpadSensSlider; /* Cursor mode */
  Fl_Choice *touchpadKindChoice; /* Button mode: kind */
  Fl_Choice *touchpadValueChoice; /* Button mode: value */
  Fl_Group *logsTab;
  Fl_Text_Display *logsDisplay;
  Fl_Output *ja2JsonPathOutput;
  Fl_Button *ja2JsonReloadBtn;
  Fl_Button *ja2JsonSaveBtn;
};
#endif
