/* OldGameVM modification notice
 * This file was changed for OldGameVM in July 2026.
 * It is not the original file. See NOTICE.md.
 */
// generated by Fast Light User Interface Designer (fluid) version 1.0309
// OGVM-LAYOUTB: hand-edited layout (radio-first Data tab; no fluid on build machine)

#include "StracciatellaLauncher.h"

StracciatellaLauncher::StracciatellaLauncher() {
  { stracciatellaLauncher = new Fl_Double_Window(520, 470, "JA2 Stracciatella Launcher");
    stracciatellaLauncher->user_data((void*)(this));
    { tabs = new Fl_Tabs(0, 0, 520, 440);
      tabs->align(Fl_Align(FL_ALIGN_TOP_RIGHT));
      { Fl_Group* o = new Fl_Group(0, 50, 520, 390, "@> Play  ");
        o->labelsize(16);
        o->labelcolor((Fl_Color)24);
        { editorButton = new Fl_Button(160, 170, 200, 25, "Start Map Editor");
        } // Fl_Button* editorButton
        { playButton = new Fl_Button(160, 205, 200, 55, "Play Ja2 Stracciatella");
        } // Fl_Button* playButton
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 50, 520, 390, "@filenew Data ");
        o->labelcolor((Fl_Color)24);
        o->hide();
        /* OGVM-LAYOUTB --------------------------------------------------------
         * Radio-first Data tab:
         *  1) status line
         *  2) two source radios
         *  3) exclusive panels (installer import XOR existing folder)
         *  4) language / saves / detect (always visible)
         */
        { sourceStatusLabel = new Fl_Box(20, 58, 480, 22, "Choose how you have the game data");
          sourceStatusLabel->box(FL_NO_BOX);
          sourceStatusLabel->labelfont(FL_HELVETICA);   /* OGVM-READYSTYLE: 12pt, not bold */
          sourceStatusLabel->labelsize(12);
          sourceStatusLabel->labelcolor(FL_DARK_GREEN);
          sourceStatusLabel->align(Fl_Align(FL_ALIGN_LEFT | FL_ALIGN_INSIDE));
        }
        { sourceInstallerRadio = new Fl_Round_Button(20, 86, 480, 24,
            "I have a GOG installer file (.exe) - import it here");
          sourceInstallerRadio->down_box(FL_ROUND_DOWN_BOX);
          sourceInstallerRadio->type(FL_RADIO_BUTTON);
          sourceInstallerRadio->labelsize(13);
          sourceInstallerRadio->tooltip("Import game data from a GOG or retail setup_*.exe without installing the original game.");
        }
        { sourceFolderRadio = new Fl_Round_Button(20, 112, 480, 24,
            "I already have a game folder (Steam, or an installed copy)");
          sourceFolderRadio->down_box(FL_ROUND_DOWN_BOX);
          sourceFolderRadio->type(FL_RADIO_BUTTON);
          sourceFolderRadio->labelsize(13);
          sourceFolderRadio->tooltip("Point at a Steam Wineskin folder or any already-installed JA2 data folder.");
          sourceFolderRadio->value(1);
        }
        { /* Installer-only panel (same slot as folder panel; only one shown) */
          ogvmInstallerPanel = new Fl_Group(10, 142, 500, 72);
          ogvmInstallerPanel->box(FL_NO_BOX);
          { importGameDataButton = new Fl_Button(20, 150, 480, 32, "Import from installer...");
            importGameDataButton->tooltip("Extract game data straight from a GOG or retail installer.");
          }
          { importProgress = new Fl_Progress(20, 190, 480, 18, "");
            importProgress->minimum(0.0f);
            importProgress->maximum(100.0f);
            importProgress->value(0.0f);
            importProgress->labelsize(12);
            importProgress->selection_color(FL_GREEN);   /* OGVM-PROGCOLOR */
            importProgress->hide();
          }
          ogvmInstallerPanel->end();
          ogvmInstallerPanel->hide();   /* default: existing-folder path */
        }
        { /* Existing-folder panel */
          ogvmFolderPanel = new Fl_Group(10, 142, 500, 72);
          ogvmFolderPanel->box(FL_NO_BOX);
          { gameDirectoryInput = new Fl_Input(20, 160, 440, 30, "JA2 game folder:");
            gameDirectoryInput->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            Fl_Group::current()->resizable(gameDirectoryInput);
          }
          { browseJa2DirectoryButton = new Fl_Button(470, 160, 30, 30, "@fileopen");
            browseJa2DirectoryButton->tooltip("Choose JA2 game directory.");
          }
          ogvmFolderPanel->end();
        }
        { Fl_Group* g = new Fl_Group(10, 222, 500, 50);
          { gameVersionInput = new Fl_Choice(20, 242, 440, 30, "Data language:");
            gameVersionInput->down_box(FL_BORDER_BOX);
            gameVersionInput->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            Fl_Group::current()->resizable(gameVersionInput);
          }
          { guessVersionButton = new Fl_Button(470, 242, 30, 30, "@search");
            guessVersionButton->tooltip("Guess Game Version");
          }
          g->end();
        }
        { Fl_Group* g = new Fl_Group(10, 278, 500, 50);
          { saveGameDirectoryInput = new Fl_Input(20, 298, 440, 30, "Saved games folder (optional):");
            saveGameDirectoryInput->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            Fl_Group::current()->resizable(saveGameDirectoryInput);
          }
          { browseSaveGameDirectoryButton = new Fl_Button(470, 298, 30, 30, "@fileopen");
            browseSaveGameDirectoryButton->tooltip("Choose save game directory.");
          }
          g->end();
        }
        { detectEditionButton = new Fl_Button(20, 340, 220, 28, "Detect Edition");
          detectEditionButton->tooltip("Show matched files and detection details for the current game folder.");
        }
        { Fl_Group* g = new Fl_Group(10, 375, 500, 20, "resizable");
          g->labeltype(FL_NO_LABEL);
          g->align(Fl_Align(FL_ALIGN_TOP|FL_ALIGN_INSIDE));
          g->end();
          Fl_Group::current()->resizable(g);
        }
        o->end();
      } // Fl_Group* Data
      { Fl_Group* o = new Fl_Group(0, 50, 520, 390, "@-> Mods ");
        o->labelcolor((Fl_Color)24);
        o->hide();
        { Fl_Group* g = new Fl_Group(10, 80, 500, 165);
          { enabledModsBrowser = new Fl_Browser(20, 95, 215, 150, "Enabled Mods:");
            enabledModsBrowser->type(3);
            enabledModsBrowser->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          }
          { enableModsButton = new Fl_Button(245, 95, 30, 30, "@<");
            enableModsButton->tooltip("Enable one or multiple mods.");
            enableModsButton->deactivate();
          }
          { disableModsButton = new Fl_Button(245, 135, 30, 30, "@>");
            disableModsButton->tooltip("Disable one or multiple mods.");
            disableModsButton->deactivate();
          }
          { moveUpModsButton = new Fl_Button(245, 175, 30, 30, "@2<");
            moveUpModsButton->tooltip("Move mod up in the list and decrease mod priority.");
            moveUpModsButton->deactivate();
          }
          { moveDownModsButton = new Fl_Button(245, 215, 30, 30, "@8<");
            moveDownModsButton->tooltip("Move mod down in the list and increase mod priority.");
            moveDownModsButton->deactivate();
          }
          { availableModsBrowser = new Fl_Browser(285, 95, 215, 150, "Disabled Mods:");
            availableModsBrowser->type(3);
            availableModsBrowser->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          }
          g->end();
        }
        { modDetails = new Fl_Text_Display(20, 255, 480, 80);
          modDetails->color((Fl_Color)55);
          modDetails->hide();
        }
        { Fl_Box* b = new Fl_Box(17, 55, 480, 20, "Mods listed later in the \"Enabled Mods\" list have higher priority.");
          b->tooltip("Higher priority mods can overwrite changes from lower-priority ones or build on their features.");
          b->align(Fl_Align(133|FL_ALIGN_INSIDE));
        }
        o->end();
      }
      { Fl_Group* o = new Fl_Group(0, 50, 520, 390, "@menu Settings ");
        o->labelcolor((Fl_Color)24);
        o->hide();
        { Fl_Group* g = new Fl_Group(10, 60, 500, 45);
          { gameSettingsOutput = new Fl_Output(20, 75, 480, 30, "Game Settings:");
            gameSettingsOutput->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            Fl_Group::current()->resizable(gameSettingsOutput);
          }
          g->end();
        }
        { Fl_Group* g = new Fl_Group(10, 115, 500, 52);
          g->tooltip("Specify the internal rendering resolution. Text and sprites become very small at high resolutions. The strategic map screen needs at least 768 pixels of height to show the full map, so 1366x768 or larger is recommended.");
          { resolutionXInput = new Fl_Value_Input(20, 130, 75, 30, "Internal Resolution:");
            resolutionXInput->minimum(640);
            resolutionXInput->maximum(0);
            resolutionXInput->value(640);
            resolutionXInput->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          }
          { new Fl_Box(95, 130, 20, 30, "x"); }
          { resolutionYInput = new Fl_Value_Input(115, 130, 75, 30);
            resolutionYInput->labeltype(FL_NO_LABEL);
            resolutionYInput->minimum(480);
            resolutionYInput->maximum(0);
            resolutionYInput->value(480);
            resolutionYInput->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          }
          { predefinedResolutionMenuButton = new Fl_Menu_Button(210, 130, 110, 30, "Predefined"); }
          { Fl_Group* r = new Fl_Group(415, 115, 30, 30, "resizable");
            r->labeltype(FL_NO_LABEL);
            r->align(Fl_Align(FL_ALIGN_TOP|FL_ALIGN_INSIDE));
            r->end();
            Fl_Group::current()->resizable(r);
          }
          { invalidResolutionLabel = new Fl_Box(340, 130, 160, 30, "invalid!");
            invalidResolutionLabel->tooltip("the resolution must be at least 640x480, the original game resolution; 1366x768 or larger is recommended so the strategic map fits");
            invalidResolutionLabel->labelfont(1);
            invalidResolutionLabel->labelcolor((Fl_Color)1);
            invalidResolutionLabel->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
          }
          g->end();
        }
        { Fl_Group* g = new Fl_Group(10, 170, 500, 55);
          g->tooltip("Choose a scaling mode to stretch the game video to fit the screen.");
          { scalingModeChoice = new Fl_Choice(20, 185, 480, 30, "Scaling Mode:");
            scalingModeChoice->down_box(FL_BORDER_BOX);
            scalingModeChoice->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            Fl_Group::current()->resizable(scalingModeChoice);
          }
          g->end();
        }
        { Fl_Group* g = new Fl_Group(10, 220, 500, 65);
          { fullscreenCheckbox = new Fl_Check_Button(20, 225, 95, 30, "Fullscreen");
            fullscreenCheckbox->tooltip("Check to run in a borderless full-screen window");
            fullscreenCheckbox->down_box(FL_DOWN_BOX);
          }
          { playSoundsCheckbox = new Fl_Check_Button(20, 255, 109, 30, "Play Sounds");
            playSoundsCheckbox->down_box(FL_DOWN_BOX);
            playSoundsCheckbox->value(1);
          }
          g->end();
        }
        o->end();
      }
      { logsTab = new Fl_Group(0, 50, 520, 390, "@square Logs");
        logsTab->labelcolor((Fl_Color)24);
        logsTab->hide();
        { logsDisplay = new Fl_Text_Display(20, 95, 480, 330, "You can view the logs of the latest JA2 Stracciatella execution here. If you want to report a bug, please include them in your bug report.");
          logsDisplay->box(FL_DOWN_BOX);
          logsDisplay->align(Fl_Align(133));
          Fl_Group::current()->resizable(logsDisplay);
        }
        logsTab->end();
      }
      tabs->end();
      Fl_Group::current()->resizable(tabs);
    } // Fl_Tabs* tabs
    { Fl_Group* o = new Fl_Group(0, 440, 520, 30);
      { ja2JsonPathOutput = new Fl_Output(0, 440, 460, 30);
        ja2JsonPathOutput->tooltip("Path to stracciatella engine options");
        ja2JsonPathOutput->color(FL_BACKGROUND_COLOR);
        ja2JsonPathOutput->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
        Fl_Group::current()->resizable(ja2JsonPathOutput);
      }
      { ja2JsonReloadBtn = new Fl_Button(460, 440, 30, 30, "@reload");
        ja2JsonReloadBtn->tooltip("Reload stracciatella engine options");
        ja2JsonReloadBtn->box(FL_THIN_UP_BOX);
        ja2JsonReloadBtn->labelcolor(FL_INACTIVE_COLOR);
      }
      { ja2JsonSaveBtn = new Fl_Button(490, 440, 30, 30, "@filesave");
        ja2JsonSaveBtn->tooltip("Save stracciatella engine options");
        ja2JsonSaveBtn->box(FL_THIN_UP_BOX);
        ja2JsonSaveBtn->labelcolor(FL_INACTIVE_COLOR);
      }
      o->end();
    }
    stracciatellaLauncher->size_range(520, 480);
    stracciatellaLauncher->end();
  }
}
